version: "3.8"

services:
  web:
    image: thunes-web
    build:
      context: ./web
    volumes:
      - ./web:/app
    ports:
      - 8080:8080
    links:
      - api
  api:
    image: thunes-api
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 4000:4000
    restart: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
  db:
    image: thunes-db
    build:
      context: ./db
    restart: always
    environment:
      - POSTGRES_DB=thunes-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 6432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
